
####################################################################################
# Generated by Vivado 2019.1 built on 'Fri May 24 14:49:42 MDT 2019' by 'xbuild'
# Command Used: write_xdc -force fplan.xdc
####################################################################################


# User Generated miscellaneous constraints 

set_property HD.RECONFIGURABLE true [get_cells design_1_i/OFDM/inst/DPR_QAM_QPSK_v1_0_S00_AXI_inst/T1/UUT/DAT_Mod_Ins]
set_property HD.RECONFIGURABLE true [get_cells design_1_i/OFDM/inst/DPR_QAM_QPSK_v1_0_S00_AXI_inst/T1/UUT1/DataSymDem_ins]
set_property HD.RECONFIGURABLE true [get_cells design_1_i/MAB1/inst/u1]
set_property HD.RECONFIGURABLE true [get_cells design_1_i/MAB2/inst/u1]
set_property HD.RECONFIGURABLE true [get_cells design_1_i/MAB3/inst/u1]

# User Generated physical constraints 

create_pblock pblock_machine1
add_cells_to_pblock [get_pblocks pblock_machine1] [get_cells -quiet [list design_1_i/MAB1/inst/u1]]
resize_pblock [get_pblocks pblock_machine1] -add {SLICE_X0Y201:SLICE_X27Y249}
resize_pblock [get_pblocks pblock_machine1] -add {DSP48_X0Y82:DSP48_X1Y99}
resize_pblock [get_pblocks pblock_machine1] -add {RAMB18_X0Y82:RAMB18_X1Y99}
resize_pblock [get_pblocks pblock_machine1] -add {RAMB36_X0Y41:RAMB36_X1Y49}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_machine1]
set_property SNAPPING_MODE ON [get_pblocks pblock_machine1]

# User Generated miscellaneous constraints 


# User Generated physical constraints 

create_pblock pblock_machine2
add_cells_to_pblock [get_pblocks pblock_machine2] [get_cells -quiet [list design_1_i/MAB2/inst/u1]]
resize_pblock [get_pblocks pblock_machine2] -add {SLICE_X32Y201:SLICE_X59Y249}
resize_pblock [get_pblocks pblock_machine2] -add {DSP48_X2Y82:DSP48_X3Y99}
resize_pblock [get_pblocks pblock_machine2] -add {RAMB18_X2Y82:RAMB18_X3Y99}
resize_pblock [get_pblocks pblock_machine2] -add {RAMB36_X2Y41:RAMB36_X3Y49}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_machine2]
set_property SNAPPING_MODE ON [get_pblocks pblock_machine2]

# User Generated miscellaneous constraints 


# User Generated physical constraints 

create_pblock pblock_machine3
add_cells_to_pblock [get_pblocks pblock_machine3] [get_cells -quiet [list design_1_i/MAB3/inst/u1]]
resize_pblock [get_pblocks pblock_machine3] -add {SLICE_X0Y151:SLICE_X27Y199}
resize_pblock [get_pblocks pblock_machine3] -add {DSP48_X0Y62:DSP48_X1Y79}
resize_pblock [get_pblocks pblock_machine3] -add {RAMB18_X0Y62:RAMB18_X1Y79}
resize_pblock [get_pblocks pblock_machine3] -add {RAMB36_X0Y31:RAMB36_X1Y39}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_machine3]
set_property SNAPPING_MODE ON [get_pblocks pblock_machine3]

# User Generated miscellaneous constraints 


# User Generated physical constraints 

create_pblock pblock_Mod
add_cells_to_pblock [get_pblocks pblock_Mod] [get_cells -quiet [list design_1_i/OFDM/inst/DPR_QAM_QPSK_v1_0_S00_AXI_inst/T1/UUT/DAT_Mod_Ins]]
resize_pblock [get_pblocks pblock_Mod] -add {SLICE_X30Y183:SLICE_X43Y199}
resize_pblock [get_pblocks pblock_Mod] -add {DSP48_X2Y74:DSP48_X2Y79}
resize_pblock [get_pblocks pblock_Mod] -add {RAMB18_X2Y74:RAMB18_X2Y79}
resize_pblock [get_pblocks pblock_Mod] -add {RAMB36_X2Y37:RAMB36_X2Y39}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_Mod]
set_property SNAPPING_MODE ON [get_pblocks pblock_Mod]

# User Generated miscellaneous constraints 


# User Generated physical constraints 

create_pblock pblock_Demod
add_cells_to_pblock [get_pblocks pblock_Demod] [get_cells -quiet [list design_1_i/OFDM/inst/DPR_QAM_QPSK_v1_0_S00_AXI_inst/T1/UUT1/DataSymDem_ins]]
resize_pblock [get_pblocks pblock_Demod] -add {SLICE_X46Y182:SLICE_X61Y199}
resize_pblock [get_pblocks pblock_Demod] -add {DSP48_X3Y74:DSP48_X3Y79}
resize_pblock [get_pblocks pblock_Demod] -add {RAMB18_X3Y74:RAMB18_X3Y79}
resize_pblock [get_pblocks pblock_Demod] -add {RAMB36_X3Y37:RAMB36_X3Y39}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_Demod]
set_property SNAPPING_MODE ON [get_pblocks pblock_Demod]

# User Generated miscellaneous constraints 


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
